# Generated by Django 4.2.4 on 2023-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], default='single', max_length=10),
        ),
    ]
