# Generated by Django 4.2.4 on 2023-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_guest_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], default='single', max_length=10),
        ),
    ]
