# Generated by Django 4.2.4 on 2023-08-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_type',
        ),
    ]
